#!/usr/bin/env python3
"""DarkAges Report Generator

Generates Markdown + JSON demo reports with validation results, metrics, screenshots.
"""

import json
import time
from pathlib import Path
from typing import List, Optional, Dict

PROJECT_ROOT = Path("/root/projects/DarkAges")
ARTIFACTS = PROJECT_ROOT / "tools/demo/artifacts"


class ReportGenerator:
    def __init__(self, output_dir: Path = ARTIFACTS / "reports"):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        duration_sec: float,
        mode: str,
        npcs: int,
        git_commit: str,
        checks: List[Dict],
        metrics_summary: Optional[Dict] = None,
        screenshot_paths: Optional[List[Path]] = None,
        chaos_results: Optional[List[Dict]] = None,
    ) -> Path:
        ts = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
        fname = f"Demo_Report_{time.strftime('%Y%m%d_%H%M%S')}"
        md_path = self.output_dir / f"{fname}.md"
        json_path = self.output_dir / f"{fname}.json"

        passed = sum(1 for c in checks if c.get("passed"))
        total = len(checks)

        md_lines = [
            "# DarkAges Demo Report",
            f"**Date:** {ts}",
            f"**Duration:** {duration_sec:.1f}s",
            f"**Git Commit:** {git_commit}",
            f"**Mode:** {mode}",
            f"**NPCs:** {npcs}",
            "",
            "## Results",
            "| Check | Status | Detail |",
            "|-------|--------|--------|",
        ]
        for c in checks:
            status = "PASS" if c.get("passed") else "FAIL"
            md_lines.append(f"| {c.get('name','?')} | {status} | {c.get('detail','')} |")

        md_lines += [
            "",
            f"**Overall:** {passed}/{total} checks passed",
            "",
        ]

        if metrics_summary:
            md_lines += [
                "## Performance",
                f"- Server Memory p50: {metrics_summary.get('server_memory_p50_mb', 'N/A')} MB",
                f"- Server Memory Max: {metrics_summary.get('server_memory_max_mb', 'N/A')} MB",
                f"- CPU Avg: {metrics_summary.get('cpu_avg', 'N/A')}%",
                f"- Memory Peak: {metrics_summary.get('memory_peak_percent', 'N/A')}%",
                "",
            ]

        if chaos_results:
            md_lines += [
                "## Chaos Injection",
                "| Action | Status | Detail |",
                "|--------|--------|--------|",
            ]
            for r in chaos_results:
                md_lines.append(f"| {r.get('action','?')} | {r.get('status','?')} | {r.get('reason','')} |")
            md_lines.append("")

        if screenshot_paths:
            md_lines += ["## Screenshots", ""]
            for p in screenshot_paths:
                md_lines.append(f"![Screenshot]({p.name})")
            md_lines.append("")

        md_lines += [
            "## Artifacts",
            f"- Report JSON: {json_path}",
            f"- Artifacts: {ARTIFACTS}",
            "",
            "*Generated by DarkAges Demo Pipeline*",
        ]

        md_path.write_text("\n".join(md_lines))

        json_data = {
            "timestamp": ts,
            "duration_sec": duration_sec,
            "git_commit": git_commit,
            "mode": mode,
            "npcs": npcs,
            "checks": checks,
            "metrics_summary": metrics_summary,
            "chaos_results": chaos_results,
            "screenshots": [str(p) for p in (screenshot_paths or [])],
        }
        json_path.write_text(json.dumps(json_data, indent=2))

        return md_path
